type: object
properties:
  name:
    type: string
  age:
    type: string
  labels:
    type: object
    additionalProperties:
      type: string
  data:
    type: object
    additionalProperties:
      type: string
  createTime:
    type: integer
