type: object
properties:
  id:
    type: integer
    description: 在请求体中无效
    enum:
      - 1
  name:
    type: string
    enum:
      - koderover
      - ldap
  description:
    type: string
    enum:
      - 发布系统
  default_branch:
    type: string
    enum:
      - master
