type: object
properties:
  id:
    type: integer
    description: 在请求体中无效
    enum:
      - 1
  name:
    type: string
    example: koderover
  description:
    type: string
    example: 发布系统
  default_branch:
    type: string
    example: master
