openapi: 3.0.0
servers:
  - description: Poetry API Auto Mocking
    url: 'https://virtserver.swaggerhub.com/zhuzhan_poetry/poetry_api/1.0.0-rc'
info:
  version: 1.0.0-rc
  title: Poetry api
  description: 'Poetry api协议, 分页协议参考https://docs.gitlab.com/ee/api/#pagination-link-header'
